// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPBzTPXMeU_Kx-dtJOEbLzCQgKMdsbRkA',
    appId: '1:471331961561:web:4751ceeb77bf51a7435cc8',
    messagingSenderId: '471331961561',
    projectId: 'bill-tracker-system',
    authDomain: 'bill-tracker-system.firebaseapp.com',
    storageBucket: 'bill-tracker-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyTkm--HkTiPREYDplxV1XI4Qplb0JJd8',
    appId: '1:471331961561:android:1ee2d6cc0613349d435cc8',
    messagingSenderId: '471331961561',
    projectId: 'bill-tracker-system',
    storageBucket: 'bill-tracker-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGACu0S2wBWeHr0xw_-e2ya4n01rC4cXk',
    appId: '1:471331961561:ios:b5346f35ae408165435cc8',
    messagingSenderId: '471331961561',
    projectId: 'bill-tracker-system',
    storageBucket: 'bill-tracker-system.firebasestorage.app',
    iosBundleId: 'com.example.billTracker',
  );

}